CREATE TABLE IF NOT EXISTS prospects_stream (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tenant TEXT,
    software TEXT,
    version TEXT,
    tag TEXT,
    processed  BOOLEAN DEFAULT FALSE,
    prefixttl TEXT,
    individualname TEXT,
    firstname TEXT,
    middlename TEXT,
    lastname TEXT,
    address TEXT,
    address2line TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    zip4 TEXT,
    country TEXT,
    dpbc TEXT,
    confidencecode TEXT,
    ageofindividual TEXT,
    addrtypeind TEXT,
    networthprem TEXT,
    estincome TEXT,
    homeownren TEXT,
    hownrenfl TEXT,
    dsfwalksequence TEXT,
    crrt TEXT,
    areacode TEXT,
    phone TEXT,
    phone_nospace TEXT,
    phoneflag TEXT,
    yearhomebuilt TEXT,
    hub_plus_import_id INT
);

-- ALTER TABLE prospects_stream
--     OWNER TO unification_ingest_admin;
