#!/bin/bash

# Check if components from csvkit are installed
if ! command -v in2csv &> /dev/null
then
    echo "Error: in2csv is not installed. Please install it to proceed." >&2
    exit 1
else
    echo "in2csv is installed"
fi
