#file: noinspection SpellCheckingInspection
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                schema_filter: ~^(?!hdb_catalog|lock_keys|temp_)~
            messenger:
                url: '%env(resolve:MESSENGER_DATABASE_URL)%'
            ingest:
                url: '%env(resolve:INGEST_DATABASE_URL)%'
            unification:
                url: '%env(resolve:UNIFICATION_DATABASE_URL)%'
            certainpath:
                url: '%env(resolve:CERTAINPATH_DSN)%'
            serviceline:
                url: '%env(resolve:SERVICELINE_DSN)%'
            generic_ingest:
                url: '%env(resolve:GENERIC_INGEST_DSN)%'
            craft_cms:
                url: '%env(resolve:CRAFT_DSN)%'
        default_connection: default
        types:
            tsvector: App\Doctrine\Types\TsVectorType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
    orm:
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: default
                report_fields_where_declared: true
                validate_xml_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    ServiceTitan:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Module/ServiceTitan/Entity'
                        prefix: 'App\Module\ServiceTitan\Entity'
                        alias: ServiceTitan
                dql:
                    string_functions:
                        WEBCSEARCH_TO_TSQUERY: App\Doctrine\WebsearchToTsquery
                        TSMATCH: App\Doctrine\Tsmatch

                        #            quickbooks_reporting:
#                connection: quickbooks_reporting
#                mappings:
#                    Unification:
                        #mapping: true
                        #type: attribute
#                        is_bundle: false
#                        dir: '%kernel.project_dir%/src/Entity/Unification'
#                        prefix: 'App\Entity\Unification'
#                        alias: Unification
        #auto_generate_proxy_classes: true
        #enable_lazy_ghost_objects: true
#        auto_mapping: true
#        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity/HubPlus'
#                prefix: 'App\Entity'
#                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
