monolog:
    channels:
        - deprecation
        - quickbooks_reporting

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            quickbooks_reporting:
                type: stream
                path: "%kernel.logs_dir%/quickbooks_reporting_%kernel.environment%.log"
                level: debug
                channels: ["quickbooks_reporting"]
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            quickbooks_reporting:
                type: stream
                path: "%kernel.logs_dir%/quickbooks_reporting_%kernel.environment%.log"
                level: debug
                channels: ["quickbooks_reporting"]
                formatter: monolog.formatter.json

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: info
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
            quickbooks_reporting:
                type: stream
                path: "%kernel.logs_dir%/quickbooks_reporting_%kernel.environment%.log"
                level: error
                channels: ["quickbooks_reporting"]
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
