nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Company-UUID', 'X-Impersonate-User-UUID']
        expose_headers: ['Content-Type', 'Authorization', 'X-Company-UUID', 'X-Impersonate-User-UUID', 'Content-Disposition']
        max_age: 3600
    paths:
        '^/api/public/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_credentials: true
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Company-UUID', 'X-Impersonate-User-UUID']
            expose_headers: ['Content-Type', 'Authorization', 'X-Company-UUID', 'X-Impersonate-User-UUID', 'Content-Disposition']
            max_age: 3600
