<?php

namespace App\ValueObject;

use App\Exception\CouldNotReadSheet;
use App\Exception\ExcelFileIsCorrupted;
use App\Exception\FieldsAreMissing;
use App\Exception\NoFilePathWasProvided;
use App\Exception\UnsupportedFileTypeException;
use League\Csv\Exception;
use League\Csv\SyntaxError;
use League\Csv\UnavailableStream;
use OpenSpout\Common\Exception\IOException;
use OpenSpout\Reader\Exception\ReaderNotOpenedException;

class CampaignProductTaxonomy
{
    private const array CAMPAIGN_PRODUCTS = [
        [
            'name' => 'Letter:1 page Letter #10',
            'type' => self::SERVICE,
            'description' => '1 page #10 Envelope Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'standard',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '1 page #10 Envelope Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:2 page Letter #10',
            'type' => self::SERVICE,
            'description' => '2 page #10 Envelope Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'standard',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '2 page #10 Envelope Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:2 page Letter #10 with Print',
            'type' => self::SERVICE,
            'description' => '2 page #10 Envelope Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'standard',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '2 page #10 Envelope Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Buy Back Letter',
            'type' => self::SERVICE,
            'description' => '6x9 Envelope Buy Back Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'buy_back',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '6x9 Envelope Buy Back Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Plumbing Buy Back Letter',
            'type' => self::SERVICE,
            'description' => '6x9 Envelope Plumbing Buy Back Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'buy_back',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '6x9 Envelope Plumbing Buy Back Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Customer Letter - Buy Back',
            'type' => self::SERVICE,
            'description' => '6x9 Envelope Buy Back Letter targeting CUSTOMERS in supplied zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'buy_back',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '6x9 Envelope Buy Back Letter targeting CUSTOMERS in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::CUSTOMERS,
        ],
        [
            'name' => 'Letter:Customer Letter - Sell Us',
            'type' => self::SERVICE,
            'description' => '6x9 Envelope Sell Us Letter targeting CUSTOMERS in supplied zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'sell_us',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '6x9 Envelope Sell Us Letter targeting CUSTOMERS in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::CUSTOMERS,
        ],
        [
            'name' => 'Letter:Customer Letter - 4 Color Customer Close Out Letter',
            'type' => self::SERVICE,
            'description' => '2 page Four Color Letter in a #10 Envelope targeting CUSTOMERS in supplied zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'close_out',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => null,
            'customerPrice' => '0.70',
            'mailerDescription' => '2 page Four Color Letter in a #10 Envelope targeting CUSTOMERS in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::CUSTOMERS,
        ],
        [
            'name' => 'Letter:Excess Inventory Letter',
            'type' => self::SERVICE,
            'description' => '#10 Envelope Excess Inventory Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'inventory',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '#10 Envelope Excess Inventory Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Free Furnace Letter',
            'type' => self::SERVICE,
            'description' => '#10 Envelope Free Furnace Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'furnace',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '#10 Envelope Free Furnace Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Trade In Letter',
            'type' => self::SERVICE,
            'description' => '#10 Envelope Trade In Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'trade_in',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '#10 Envelope Trade In Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Frustrated Contractor Letter',
            'type' => self::SERVICE,
            'description' => '#10 Envelope Frustrated Contractor Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'contractor',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '#10 Envelope Frustrated Contractor Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Rebate Letter',
            'type' => self::SERVICE,
            'description' => '#10 Envelope Rebate Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'rebate',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '#10 Envelope Rebate Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Sell Us Letter',
            'type' => self::SERVICE,
            'description' => '6x9  Envelope Sell Us Letter targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'sell_us',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '6x9  Envelope Sell Us Letter targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Sell Us Letter - Color',
            'type' => self::SERVICE,
            'description' => '6x9 Envelope Sell Us Letter - Color targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'sell_us',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.73',
            'customerPrice' => '0.77',
            'mailerDescription' => '6x9 Envelope Sell Us Letter - Color targeting customers in zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter:Tune Up Letter',
            'type' => self::SERVICE,
            'description' => '1 Page Four Color 2 Sides Tune Up Letter in a #10 envelope targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'tune_up',
            'format' => self::NUMBER_10_ENVELOPE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '1 Page Four Color 2 Sides Tune Up Letter in a #10 envelope targeting customers in supplied zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:AC or FURNACE Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 A/C or Furnace Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'furnace',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 A/C or Furnace Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Furnace or AC Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Furnace or AC Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'furnace',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Furnace or AC Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:AC Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:AC Tune Up Postcard - GREEN Stock',
            'type' => self::SERVICE,
            'description' => '4.25x6 Tune Up Postcard (GREEN stock) targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Tune Up Postcard (GREEN stock) targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => true,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Solar/HVAC Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '6x4.25 Solar/HVAC tune up postcard',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '6x4.25 Solar/HVAC tune up postcard',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS_AND_CUSTOMERS,
        ],
        [
            'name' => 'Postcard:AC Tune Up Postcard - YELLOW Stock',
            'type' => self::SERVICE,
            'description' => '4.25x6 Tune Up Postcard (YELLOW stock) targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Tune Up Postcard (YELLOW stock) targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => true,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone AC Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Cornerstone AC Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Cornerstone AC Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone Combo Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Cornerstone Combo Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Cornerstone Combo Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone Furnace Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Cornerstone Furnace Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'furnace',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Cornerstone Furnace Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone Drain Cleaning Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Cornerstone Drain Cleaning Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'drain_cleaning',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Cornerstone Drain Cleaning Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone Water Heater Flush Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Cornerstone Water Heater Flush Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'water_heater',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Cornerstone Water Heater Flush Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Cornerstone Electric Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Cornerstone Electric Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'electric',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.57',
            'customerPrice' => '0.61',
            'mailerDescription' => '4.25x6 Cornerstone Electric Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Cornerstone',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Customer Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Postcard targeting CUSTOMERS in supplied zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Postcard targeting CUSTOMERS in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::CUSTOMERS,
        ],
        [
            'name' => 'Postcard:Combo Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 HVAC & Plumbing Combo Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'tune_up',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 HVAC & Plumbing Combo Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Electric Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Electric Service Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'electric',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Electric Service Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Furnace Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Furnace Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'furnace',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Furnace Tune Up Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Roofing Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Roofing Service Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'roofing',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Roofing Service Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Plumbing Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Plumbing Service Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'plumbing',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Plumbing Service Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Standard Postcard 11.5x5.5',
            'type' => self::SERVICE,
            'description' => '11x5.5 Oversized Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'oversized',
            'format' => self::OVERSIZED,
            'prospectPrice' => null,
            'customerPrice' => null,
            'mailerDescription' => '11x5.5 Oversized Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '11x5.5',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Drain Cleaning Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Drain Cleaning Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'drain_cleaning',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Drain Cleaning Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Water Heater Flush Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Water Heater Flush Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'water_heater',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '4.25x6 Water Heater Flush Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:4/4 Replacement Postcard 8.5x5.5',
            'type' => self::SERVICE,
            'description' => '4/4 Replacement Postcard 8.5x5.5 targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'replacement',
            'format' => 'Medium Size',
            'prospectPrice' => null,
            'customerPrice' => null,
            'mailerDescription' => '4/4 Replacement Postcard 8.5x5.5 targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x5.5',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:4 Color Drain Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Plumbing Drain Service Postcard',
            'category' => self::POSTCARDS,
            'subCategory' => 'drain_cleaning',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '4.25x6 Plumbing Drain Service Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS_AND_CUSTOMERS,
        ],
        [
            'name' => 'Postcard:System Replacement Postcard',
            'type' => self::SERVICE,
            'description' => '6x4.25 System Replacement Postcard',
            'category' => self::POSTCARDS,
            'subCategory' => 'replacement',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.56',
            'customerPrice' => '0.60',
            'mailerDescription' => '6x4.25 System Replacement Postcard targeting customers in supplied zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS_AND_CUSTOMERS,
        ],
        [
            'name' => 'Postcard:4 Color Two Side 6x9 Postcard',
            'type' => self::SERVICE,
            'description' => '6x9 Four Color Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.73',
            'customerPrice' => '0.77',
            'mailerDescription' => '6x9 Four Color Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard: 6x4.25 Postcard (7pt white stock 4/c 2 sides with bleed)',
            'type' => self::SERVICE,
            'description' => '6x4.25 Postcard (7pt white stock 4/c 2 sides with bleed) targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.62',
            'customerPrice' => null,
            'mailerDescription' => '',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Letter: 1 page 2 sides 4-color Letter (8 1/2x11 70lb white stock)',
            'type' => self::SERVICE,
            'description' => '1 page 2 sides 4-color Letter (8 1/2x11 70lb white stock) targeting prospects in zip code(s)',
            'category' => self::LETTERS,
            'subCategory' => 'standard',
            'format' => 'Standard Size',
            'prospectPrice' => '0.77',
            'customerPrice' => null,
            'mailerDescription' => '',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '8.5x11',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Fix-it 24/7 4 Color Two Side 6x9 Postcard',
            'type' => self::SERVICE,
            'description' => '6x9 Four Color Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.65',
            'customerPrice' => null,
            'mailerDescription' => '6x9 Four Color Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Fix-it 24/7',
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Mister Quik Furnace Tune Up Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Furnace Tune Up Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'furnace',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.53',
            'customerPrice' => null,
            'mailerDescription' => '4.25x6 Furnace Tune Up Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Mister Quik',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Monarch Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.60',
            'customerPrice' => null,
            'mailerDescription' => '4.25x6 Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Monarch',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Dring Postcard',
            'type' => self::SERVICE,
            'description' => '4.25x6 Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::STANDARD_SIZE,
            'prospectPrice' => '0.54',
            'customerPrice' => null,
            'mailerDescription' => '4.25x6 Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Dring',
            'size' => '4.25x6',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Melfi Postcard',
            'type' => self::SERVICE,
            'description' => '6x9 Four Color Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.59',
            'customerPrice' => '0.59',
            'mailerDescription' => '6x9 Four Color Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Melfi',
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:Same Day 4 Color Two Side 6x9 Postcard',
            'type' => self::SERVICE,
            'description' => '6x9 Four Color Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.66',
            'customerPrice' => '0.70',
            'mailerDescription' => '6x9 Four Color Postcard targeting customers in zip code(s)',
            'code' => 'LTR',
            'hasColoredStock' => false,
            'brand' => 'Same Day',
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
        [
            'name' => 'Postcard:6x9 EDDM Postcards - 4/4 with full bleed on 9pt Matte',
            'type' => self::SERVICE,
            'description' => '6x9 EDDM Postcards - 4/4 with full bleed on 9pt Matte',
            'category' => self::POSTCARDS,
            'subCategory' => 'eddm',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.52',
            'customerPrice' => '0.52',
            'mailerDescription' => '6x9 EDDM Postcards - 4/4 with full bleed on 9pt Matte',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => null,
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS_AND_CUSTOMERS,
        ],
        [
            'name' => 'Postcard:Morevent 4 Color Two Side 6x9 Postcard',
            'type' => self::SERVICE,
            'description' => '6x9 Morevent Four Color Postcard targeting prospects in zip code(s)',
            'category' => self::POSTCARDS,
            'subCategory' => 'standard',
            'format' => self::ENVELOPE_SIZE_6X9,
            'prospectPrice' => '0.54',
            'customerPrice' => null,
            'mailerDescription' => '6x9 Morevent Four Color Postcard targeting customers in zip code(s)',
            'code' => 'PC',
            'hasColoredStock' => false,
            'brand' => 'Morevent',
            'size' => '6x9',
            'distributionMethod' => self::DIRECT_MAIL,
            'targetAudience' => self::PROSPECTS,
        ],
    ];
    public const string DIRECT_MAIL = 'direct_mail';
    public const string PROSPECTS_AND_CUSTOMERS = 'prospects_and_customers';
    public const string PROSPECTS = 'prospects';
    public const string POSTCARDS = 'postcards';
    public const string LETTERS = 'letters';
    public const string SERVICE = 'service';
    public const string CUSTOMERS = 'customers';
    public const string NUMBER_10_ENVELOPE = '#10 Envelope';
    public const string ENVELOPE_SIZE_6X9 = '6x9 Envelope';
    public const string STANDARD_SIZE = 'Standard Size';
    public const string OVERSIZED = 'Oversized';
    public const string MEDIUM_SIZE = 'Medium Size';

    private array $csvRecords;

    /**
     * @throws IOException
     * @throws FieldsAreMissing
     * @throws UnsupportedFileTypeException
     * @throws ExcelFileIsCorrupted
     * @throws UnavailableStream
     * @throws ReaderNotOpenedException
     * @throws CouldNotReadSheet
     * @throws SyntaxError
     * @throws Exception
     * @throws NoFilePathWasProvided
     */
    public function __construct(
        private readonly ?string $csvFile = null
    ) {
        if ($this->csvFile) {
            $tabularTaxonomy = TabularFile::fromExcelOrCsvFile(
                new CampaignProductRecordMap(),
                $this->csvFile,
            );
            $this->csvRecords = [];
            foreach (
                $tabularTaxonomy->getRowIteratorForColumns(
                    $tabularTaxonomy->getHeadersAsArray()
                ) as $row
            ) {
                /** @var CampaignProductRecord $record */
                $record = CampaignProductRecord::fromTabularRecord($row);
                $record->populateFields();
                $arrayRecord = $record->toArray();
                unset($arrayRecord['meta']);
                if (empty($arrayRecord['hasColoredStock'])) {
                    $arrayRecord['hasColoredStock'] = false;
                } else {
                    $arrayRecord['hasColoredStock'] = true;
                }
                $this->csvRecords[] = $arrayRecord;
            }
        }
    }


    /**
     * @throws IOException
     * @throws FieldsAreMissing
     * @throws UnsupportedFileTypeException
     * @throws ExcelFileIsCorrupted
     * @throws UnavailableStream
     * @throws ReaderNotOpenedException
     * @throws CouldNotReadSheet
     * @throws SyntaxError
     * @throws Exception
     * @throws NoFilePathWasProvided
     */
    public static function fromCsv(
        string $csvFile,
    ): self {
        return new self(
            $csvFile
        );
    }


    public function getTaxonomyForInitialization(): array
    {
        if ($this->csvFile) {
            return $this->csvRecords;
        }
        return self::CAMPAIGN_PRODUCTS;
    }
}
