controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

feature_controllers:
    resource:
        path: ../src/Module/
        namespace: App\Module
    type: attribute
