#!/usr/bin/env bash

# Interactive "Are you sure?" prompt
read -p "Are you sure you want to drop and recreate the databases and users? This will destroy all data. (y/n): " -n 1 -r
echo

# Check if the response is 'y' or 'Y'
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Operation cancelled."
    exit 1
fi

# Create Databases
echo 'Dropping existing databases' &&
dropdb --if-exists -h "$HOSTNAME" -U "$USERNAME" -W unification_ingest_generic &&
dropdb --if-exists -h "$HOSTNAME" -U "$USERNAME" -W unification_ingest_generic_test

echo 'Dropping existing users' &&
dropuser --if-exists -h "$HOSTNAME" -U "$USERNAME" -W unification_ingest_admin

echo 'Creating users' &&
createuser -d -h "$HOSTNAME" -U "$USERNAME" -W -g pg_read_server_files -g pg_write_server_files unification_ingest_admin

echo 'Creating databases' &&
createdb -E 'UTF-8' -O unification_ingest_admin -h "$HOSTNAME" -U "$USERNAME" -W unification_ingest_generic &&
createdb -E 'UTF-8' -O unification_ingest_admin -h "$HOSTNAME" -U "$USERNAME" -W unification_ingest_generic_test

echo 'Databases provisioned'