#!/usr/bin/env php
<?php

ini_set('memory_limit', '-1');
require __DIR__.'/vendor/autoload.php';


use App\Kernel;
use App\Commands\ExportCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

// Load environment variables from .env file
(new Dotenv())->bootEnv(__DIR__.'/.env');

// Bootstrap the Symfony Kernel
$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();

// Get the service container
$container = $kernel->getContainer();

// Fetch the MigrateCommand service from the container
$command = $container->get(ExportCommand::class);

// Create the application and add the command
$application = new Application();
$application->add($command);

// Set the default command
$application->setDefaultCommand($command->getName(), true);

// Run the application
$application->run();