#!/usr/bin/env bash

# Interactive "Are you sure?" prompt
read -p "Are you sure you want to drop and recreate the databases and users? This will destroy all data. (y/n): " -n 1 -r
echo

# Check if the response is 'y' or 'Y'
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Operation cancelled."
    exit 1
fi

# Create Databases
echo 'Dropping existing databases' &&
dropdb --if-exists unification &&
dropdb --if-exists unification_test &&
dropdb --if-exists unification_ingest_field_edge &&
dropdb --if-exists unification_ingest_servicetitan &&
dropdb --if-exists unification_ingest_successware &&

echo 'Dropping existing users' &&
dropuser --if-exists -U$USER unification &&
dropuser --if-exists -U$USER unification_test &&

echo 'Creating users' &&
createuser -d -hlocalhost -gpg_read_server_files -gpg_write_server_files unification &&
createuser -d -hlocalhost -gpg_read_server_files -gpg_write_server_files unification_test &&

echo 'Creating databases' &&
createdb -E 'UTF-8' -O unification -hlocalhost -Uunification unification &&
createdb -E 'UTF-8' -O unification -hlocalhost -Uunification unification_test &&
createdb -E 'UTF-8' -O unification -hlocalhost -Uunification unification_ingest_field_edge &&
createdb -E 'UTF-8' -O unification -hlocalhost -Uunification unification_ingest_servicetitan &&
createdb -E 'UTF-8' -O unification -hlocalhost -Uunification unification_ingest_successware &&


echo 'Databases provisioned'
